### ISSUE TITLE
Automatic content crawlers break the tool

### ISSUE THREAD

**Issue by fdammeke** [paulherbosch/onetimesecret#2]
A secret automatically expires whenever an automatic content crawler (like whatsapp) accesses the secret you're sharing with someone.

**Comment by paulherbosch** [comment]
Solved via https://github.com/paulherbosch/onetimesecret/commit/eb4095ec098e092dd00c3958548c50cb9cc3146b#diff-cc95738088603531796e0d0f246a5d77
