### ISSUE TITLE
Lowercase the mail adress if a custom secret it created

### ISSUE THREAD

**Issue by fdammeke** [paulherbosch/onetimesecret#4]
In case someone pasted a mail adress with capitals inside, the recipient might not know which letters were capital. example: Some.Girl@example.tld
The recipient will not be able to retrieve the secret without knowing which letters were capitals.

**Comment by paulherbosch** [comment]
Fixed by commit https://github.com/paulherbosch/onetimesecret/commit/afce5ce2e610538fdcb5b881ee2680f6a1cfc41a
